// components/registry/vue/toggle/basic.vue
<script setup lang="ts">
import { Toggle } from "@ark-ui/vue/toggle";
import { Bold } from "lucide-vue-next";
</script>

<template>
  <div
    class="bg-white dark:bg-gray-800 w-full px-4 py-12 rounded-xl flex flex-col items-center"
  >
    <Toggle.Root
      class="inline-flex items-center justify-center p-2 rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-600 data-[state=on]:bg-blue-100 dark:data-[state=on]:bg-blue-900/30 data-[state=on]:text-blue-700 dark:data-[state=on]:text-blue-300 data-[state=on]:border-blue-300 dark:data-[state=on]:border-blue-600 transition-all"
    >
      <Bold class="w-4 h-4" />
    </Toggle.Root>
  </div>
</template>

// components/registry/svelte/checkbox/basic.svelte
<script>
  import { Checkbox } from "@ark-ui/svelte";
  import { CheckIcon } from "lucide-svelte";
</script>

<Checkbox.Root class="flex items-center gap-3 cursor-pointer">
  <Checkbox.Control
    class="w-5 h-5 bg-white border-2 border-gray-300 rounded data-[state=checked]:bg-blue-500 data-[state=checked]:border-blue-500 data-hover:border-gray-400 dark:bg-gray-900 dark:border-gray-600 dark:data-[state=checked]:bg-blue-500 dark:data-[state=checked]:border-blue-500 dark:data-hover:border-gray-400 transition-all duration-200 flex items-center justify-center"
  >
    <Checkbox.Indicator>
      <CheckIcon class="w-3.5 h-3.5 text-white" />
    </Checkbox.Indicator>
  </Checkbox.Control>
  <Checkbox.Label
    class="text-sm font-medium text-gray-900 dark:text-gray-100 cursor-pointer"
  >
    Accept terms and conditions
  </Checkbox.Label>
  <Checkbox.HiddenInput />
</Checkbox.Root>
