// components/registry/solid/radio-group/basic.tsx
import { RadioGroup } from "@ark-ui/solid/radio-group";
import { For } from "solid-js";

export default function Basic() {
  const options = ["Pizza", "Burger", "Sushi"];

  return (
    <RadioGroup.Root class="flex flex-col space-y-2">
      <RadioGroup.Indicator />
      <For each={options}>
        {(option) => (
          <RadioGroup.Item
            value={option}
            class="flex items-center gap-2 cursor-pointer"
          >
            <RadioGroup.ItemControl class="group size-4 bg-white border-2 border-gray-300 rounded-full data-[state=checked]:bg-blue-500 data-[state=checked]:border-blue-500 data-hover:border-gray-400 dark:bg-gray-900 dark:border-gray-600 dark:data-[state=checked]:bg-blue-500 dark:data-[state=checked]:border-blue-500 dark:data-hover:border-gray-400 data-focus:ring-2 data-focus:ring-blue-500/50 transition-all duration-200 flex items-center justify-center text-white">
              <svg
                width="6"
                height="6"
                viewBox="0 0 6 6"
                fill="currentcolor"
                xmlns="http://www.w3.org/2000/svg"
                class="opacity-0 group-data-[state=checked]:opacity-100 transition-opacity"
              >
                <circle cx="3" cy="3" r="3"></circle>
              </svg>
            </RadioGroup.ItemControl>
            <RadioGroup.ItemText class="text-sm font-medium">
              {option}
            </RadioGroup.ItemText>
            <RadioGroup.ItemHiddenInput />
          </RadioGroup.Item>
        )}
      </For>
    </RadioGroup.Root>
  );
}

// components/registry/svelte/segment-group/basic.svelte
<script>
  import { SegmentGroup } from "@ark-ui/svelte";

  const frameworks = ["React", "Solid", "Svelte", "Vue"];
</script>

<div class="max-w-sm w-full">
  <SegmentGroup.Root
    orientation="horizontal"
    class="flex gap-0.5 bg-gray-100 dark:bg-gray-900 relative p-1 rounded-lg"
  >
    <SegmentGroup.Indicator
      class="bg-white dark:bg-gray-800 z-10 rounded-md shadow-sm h-(--height) w-(--width) transition-all duration-200"
    />
    {#each frameworks as framework}
      <SegmentGroup.Item
        {framework}
        class="flex flex-1 items-center justify-center select-none cursor-pointer text-sm font-medium px-4 py-2 z-20 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white data-[state=checked]:text-gray-900 dark:data-[state=checked]:text-white data-disabled:cursor-not-allowed data-disabled:opacity-40 transition-colors duration-200"
      >
        <SegmentGroup.ItemText>{framework}</SegmentGroup.ItemText>
        <SegmentGroup.ItemControl />
        <SegmentGroup.ItemHiddenInput />
      </SegmentGroup.Item>
    {/each}
  </SegmentGroup.Root>
</div>
